"""Constructor API — dependency-aware component stack generation.

POST /api/constructor
Takes selected components, resolves dependencies, applies security profile,
runs pipeline, returns ZIP with compose + build artifacts.
"""
import zipfile
import io
import yaml
from datetime import datetime
from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.pipeline import Pipeline, BuildStep, ScanStep, PackageStep, RegisterStep
from app.services.dependency_resolver import DependencyResolver
from app.services.security_profiles import apply_profile, list_profiles, get_profile_info
from app.services.template_service import TemplateService
from app.services.generate_service import GenerateService

router = APIRouter(prefix="/api/constructor", tags=["constructor"])

REGISTRY_BASE = Path(__file__).parent.parent.parent / "registry"
TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

resolver = DependencyResolver()


class ConstructorRequest(BaseModel):
    components: list[str]
    profile: str = "standard"
    configs: dict[str, dict] = {}

    class Config:
        json_schema_extra = {
            "example": {
                "components": ["nginx", "nextcloud"],
                "profile": "standard",
                "configs": {"nginx": {"ports": {"80": 80}}},
            }
        }


class ConstructorDiagnostic(BaseModel):
    resolved: list[str]
    auto_added: list[dict]
    profile: dict | None = None
    errors: list[str] = []


@router.post("/diagnostic")
async def constructor_diagnostic(body: ConstructorRequest):
    """Resolve dependencies and return what would be generated (no ZIP)."""
    resolved, auto_added = resolver.resolve_with_metadata(body.components)

    errors = []
    for slug in resolved:
        manifest_path = REGISTRY_BASE / slug / "manifest.yml"
        if not manifest_path.exists():
            errors.append(f"Component '{slug}' has no manifest in registry")

    return ConstructorDiagnostic(
        resolved=resolved,
        auto_added=auto_added,
        profile=get_profile_info(body.profile),
        errors=errors,
    )


@router.post("")
async def constructor_generate(body: ConstructorRequest):
    """Generate a complete deployment package with dependency resolution."""
    # 1. Resolve dependencies
    resolved, auto_added = resolver.resolve_with_metadata(body.components)

    # 2. Validate all components exist
    manifests = {}
    for slug in resolved:
        manifest_path = REGISTRY_BASE / slug / "manifest.yml"
        if not manifest_path.exists():
            raise HTTPException(
                status_code=400,
                detail=f"Component '{slug}' not found in registry"
            )
        import yaml as ymlib
        manifests[slug] = ymlib.safe_load(manifest_path.read_text())

    # 3. Generate ZIP
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        # docker-compose.yml
        services_section = {}
        for slug in resolved:
            manifest = manifests[slug].get("component", {})
            service_def = _build_service_entry(slug, manifest, body.configs.get(slug, {}))
            services_section[slug] = service_def

        # Apply security profile
        compose = {
            "services": services_section,
            "networks": {"gosdocker": {"driver": "bridge"}},
        }
        apply_profile(compose, body.profile)

        # Write compose
        header = f"# Generated by GosDocker — Реестр гос. ИТ-компонентов\n# {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n# Profile: {body.profile}\n"
        zf.writestr("docker-compose.yml", header + yaml.dump(
            compose, default_flow_style=False, sort_keys=False, allow_unicode=True, indent=2
        ))

        # Build context for each component
        for slug in resolved:
            dockerfile_path = REGISTRY_BASE / slug / "Dockerfile"
            if dockerfile_path.exists():
                zf.write(str(dockerfile_path), f"build/{slug}/Dockerfile")

        # .env.example
        env_lines = ["# GosDocker Environment Variables", "# Generated Constructor Stack\n"]
        for slug in resolved:
            manifest = manifests[slug].get("component", {})
            for key, val in manifest.get("default_env", {}).items():
                env_lines.append(f"{slug.upper()}_{key.upper()}={val}")
        zf.writestr(".env.example", "\n".join(env_lines))

        # README.md
        readme = _build_readme(resolved, manifests, auto_added, body.profile)
        zf.writestr("README.md", readme)

    buffer.seek(0)

    # Prepare filename
    stack_name = "-".join(resolved[:3])
    if len(resolved) > 3:
        stack_name += f"-and-{len(resolved) - 3}-more"

    return StreamingResponse(
        iter([buffer.getvalue()]),
        media_type="application/zip",
        headers={
            "Content-Disposition": f"attachment; filename=gosdocker-{stack_name}.zip"
        },
    )


def _build_service_entry(slug: str, manifest: dict, config: dict) -> dict:
    """Build a single service entry for docker-compose.yml."""
    service = {
        "container_name": slug,
        "build": {
            "context": f"./build/{slug}",
            "dockerfile": "Dockerfile",
            "args": {
                "VERSION": manifest.get("version", "latest"),
            },
        },
        "networks": ["gosdocker"],
    }

    ports = manifest.get("ports", {})
    user_ports = config.get("ports", {})
    if user_ports:
        service["ports"] = [f"{ext}:{intv}" for ext, intv in user_ports.items()]
    elif ports:
        service["ports"] = [f"{intv}:{intv}" for _, intv in ports.items()]

    env = manifest.get("default_env", {})
    user_env = config.get("env", {})
    if user_env:
        service["environment"] = {**env, **user_env}
    elif env:
        service["environment"] = env

    return service


def _build_readme(resolved, manifests, auto_added, profile):
    comp_lines = []
    for slug in resolved:
        m = manifests[slug].get("component", {})
        auto_note = ""
        for aa in auto_added:
            if aa["slug"] == slug:
                auto_note = f" (автоматически: {aa['reason']})"
        comp_lines.append(f"- **{m.get('name', slug)}** v{m.get('version', '?')}{auto_note}")

    return f"""# GosDocker Stack — Конструктор

Сгенерировано: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
Профиль безопасности: {profile}

## Состав стека

{chr(10).join(comp_lines)}

## Быстрый старт

```bash
# 1. Соберите образы из исходников
docker compose build

# 2. Запустите стек
docker compose up -d
```

## Режим Air-Gapped

Для развёртывания в изолированном контуре:
1. `docker compose build` — собрать образы
2. `docker save -o images.tar <image1> <image2> ...` — экспортировать
3. Перенести `images.tar` в закрытый контур
4. `docker load -i images.tar && docker compose up -d`

## Компоненты и зависимости

Все компоненты собраны из исходного кода. Каждый сопровождается:
- ✅ Dockerfile (multi-stage build)
- ✅ SBOM (CycloneDX) — состав образа
- ✅ Trivy report — проверка уязвимостей
- ✅ Инструкция deploy.sh — для air-gapped развёртывания
"""


@router.get("/profiles")
async def list_available_profiles():
    """List available security profiles."""
    return list_profiles()
